#!/usr/bin/env python3
import os
import argparse
import shutil
import tempfile

from lib import packlib

parser = argparse.ArgumentParser(description="Tool for creating packs of Packwiz packs")
parser.add_argument("-p", "--pack", default=os.curdir, help="The pack path")
parser.add_argument("-d", "--dest-zip", default=f"{os.curdir}/build", help="The output location of the built zip.")

args = parser.parse_args()

pack_path = args.pack
extra_data = packlib.read_pack_supplementary_data(pack_path)
writer = packlib.MMCPackWriter(extra_data.slug(), pack_path)

with tempfile.TemporaryDirectory() as tmpdir:
    writer.write(tmpdir)
    os.makedirs(args.dest_zip, exist_ok=True)
    shutil.make_archive(f"{args.dest_zip}/mmc", "zip", tmpdir)
